"""added instructions column

Revision ID: 50870e75b8a0
Revises: 
Create Date: 2024-01-10 00:42:03.649189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50870e75b8a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
