"""Added thread_id to User model

Revision ID: 989b24add4f4
Revises: e135ffeddf64
Create Date: 2024-01-10 21:00:45.472152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989b24add4f4'
down_revision = 'e135ffeddf64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
