"""Added thread_id to User model

Revision ID: e135ffeddf64
Revises: b3ba83b24f0b
Create Date: 2024-01-10 19:46:18.658848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e135ffeddf64'
down_revision = 'b3ba83b24f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('chatbot_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chatbot_name', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
